apiVersion: v1
kind: Service
metadata:
  name: hello-web-service
  labels:
    app: hello
spec:
  selector:
    app: hello
    tier: web
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-web-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-web
        image: gcr.io/linebot-206417/hello-web:v2
        ports:
        - containerPort: 8080