apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-snapshots
  labels:
    app: k8s-snapshots
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-snapshots
    spec:
      containers:
      - name: k8s-snapshots
        image: elsdoerfer/k8s-snapshots:v2.0
        name: k8s-snapshots
        env:
          - name: LOG_LEVEL
            value: "DEBUG"