# Provisioner
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server-volume
  labels:
    app: nfs-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
# Replication
apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-server
  labels:
    app: nfs-server
spec:
  replicas: 1
  selector:
    role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        # https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/volume-nfs
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-server-storage
      volumes:
        - name: nfs-server-storage
          persistentVolumeClaim:
            claimName: nfs-server-volume
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server