---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-nfs-html
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # kubectl describe services nfs-server | grep -E '^IP' | cut -f2 -d':' | tr -d ' '
    server: 10.27.254.167
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-nfs-html
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 3
  selector:
    app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress
          name: wordpress
          env:
          - name: WORDPRESS_DB_HOST
            value: mysql:3306
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: password
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
          - name: nfs
            mountPath: /var/www/html
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: wordpress-nfs-html
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  loadBalancerIP: 35.229.243.229
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
      app: wordpress